# Site settings
title: VikiScripts | A Scripting Repository
description: "Collection of System Admin Scripts Written in VbScript and PowerShell."
url: "http://vikiscripts.github.io"
author:
  name: "Vikas Pandey"
  email: "vikiscripts@gmail.com"
  url: "http://vikiscripts.github.io"

# Build settings
baseurl: /MyTestBlog/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
